### ISSUE TITLE
Ability to view contributions, filter per path and/or author

### ISSUE THREAD

**Issue by renoirb** [webplatform/mediawiki-conversion#15]
Ability to visualize contributions, and changes history on the wiki and on pages in particular.
1. On a page
2. By a user
3. On a page, by a user
## Task summary
- [x] Create a view where we can query GitHub API and list commits
- [ ] Ability to filter per wiki page path (e.g. `path=content/css/properties/border-radius/index.md`)
- [ ] Ability to filter per author. Has to support both migrated users (e.g. `Dgash@docs.webplatform.org` and GitHub users (e.g. `renoirb`).
- [ ] Setup redirect from former `/wiki/Special:RecentChanges` ([example](https://docs.webplatform.org/wiki/Special:RecentChanges)) to point to **List edits**
- [ ] Setup redirect from former `/wiki/Special:Contributions/Username` ([example](https://docs.webplatform.org/wiki/Special:Contributions/Cmills)) to point to **List edits made by author**
- [ ] Setup redirect from former "page history" `/w/index.php?title=css/properties/border-radius&action=history` ([example](https://docs.webplatform.org/w/index.php?title=css/properties/border-radius&action=history)) to point to **List edits made on a page**
## Links
- [Prototype on JsFiddle](http://jsfiddle.net/renoirb/ts9p2n2n/2/), [source article](http://vuejs.org/examples/commits.html)
- [GitHub API commits](https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository)
- Views:
  - **List edits (a.k.a. Recent Changes)** [using API](https://api.github.com/repos/webplatform/docs/commits), [using GitHub](https://github.com/webplatform/docs/commits/master)
  - **List edits made on a page** [using API](https://api.github.com/repos/webplatform/docs/commits?path=content/css/properties/border-radius/index.md), [using GitHub](https://github.com/webplatform/docs/commits/master/content/css/properties/border-radius/index.md)
  - **List edits made by author migrated from MediaWiki** [using API](https://api.github.com/repos/webplatform/docs/commits?author=Cmills@docs.webplatform.org), [using GitHub](https://github.com/webplatform/docs/commits/master?author=renoirb@docs.webplatform.org)
  - **List edits made on a page by author migrated from MediaWiki** [using API](https://api.github.com/repos/webplatform/docs/commits?author=Cmills@docs.webplatform.org&path=content/css/properties/border-radius/index.md), [using GitHub](https://github.com/webplatform/docs/commits/master/content/css/properties/border-radius/index.md?author=Cmills@docs.webplatform.org)
  - **List edits made by author (after migration)** [using API](https://api.github.com/repos/webplatform/docs/commits?author=renoirb), [using GitHub](https://github.com/webplatform/docs/commits/master?author=renoirb)
## Proof of concept ScreenShot

The following is a snapshot of a [client side JavaScript client proof of concept](http://jsfiddle.net/renoirb/ts9p2n2n/2/) (ref: [source article](http://vuejs.org/examples/commits.html)) that we could use to list contributions.

![ability-view-contributions](https://cloud.githubusercontent.com/assets/296940/8987303/577ef20c-36ae-11e5-80cb-f0e910cab647.png)
